<?php
namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * MovieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovieRepository extends EntityRepository{
    protected $nbMovieByPage=5;

    /**
     * @param type $imdb
     * @return type
     */
    public function findMovieByImdb($imdb){
        $qb=$this->createQueryBuilder("m");

        $query=$qb->where('m.imdbId=:imdb')
            ->setParameter('imdb', $imdb)
            ->getQuery();

        return $query->getResult();
    }

    /**
     * @param type $name
     * @param type $p
     * @return Paginator
     */
    public function findMoviesByCategory($name, $p){
        $query = $this->getEntityManager()
            ->createQuery('
                SELECT m FROM AppBundle:Movie m
                LEFT JOIN m.categories c
                WHERE c.name=:name'
            )->setParameter('name', $name)
            ->setMaxResults($this->nbMovieByPage)
            ->setFirstResult($this->nbMovieByPage * ($p-1));

        $paginator=new Paginator($query);
        return $paginator;
    }

    public function getNbMovieByPage(){
        return $this->nbMovieByPage;
    }
}