<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TorrentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TorrentRepository extends EntityRepository{
    public function findTorrentByName($name){
        $qb=$this->createQueryBuilder("t");
        
        $query=$qb->where('t.name LIKE :name')
            ->setParameter('name', "%$name%")
            ->getQuery();
        
        return $query->getResult();
    }
    
    public function findNoBlockNoSeenTorrent(){
        $query = $this->getEntityManager()
        ->createQuery('
            SELECT t, m FROM AppBundle:Torrent t
            JOIN t.movie m
            WHERE m.block=0 AND m.seen=0'
        );
        
        return $query->getResult();
    }
}
